# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpaceApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for SpaceApp
  pod 'R.swift'

  target 'SpaceAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'KIF-Quick'
    pod 'Nimble-Snapshots'
  end
  
end
